import json

# 200+ entreprises canadiennes en génie électrique / électromécanique / automatisation
# Sources : Grandes firmes d'ingénierie, utilities, manufacturiers, mines, construction

companies = [
    # GRANDES FIRMES D'INGÉNIERIE (Québec/Ontario)
    {"company": "SNC-Lavalin", "sector": "Ingénierie - Infrastructure", "city": "Montréal, QC", "careers": "https://www.snclavalin.com/careers", "poste": "Ingénieur électrique", "type": "generale"},
    {"company": "WSP Canada", "sector": "Ingénierie - Environnement", "city": "Montréal, QC", "careers": "https://www.wsp.com/careers", "poste": "Electrical Project Engineer", "type": "generale"},
    {"company": "Stantec", "sector": "Ingénierie - Infrastructure", "city": "Edmonton, AB", "careers": "https://www.stantec.com/careers", "poste": "Electrical Design Engineer", "type": "generale"},
    {"company": "CIMA+", "sector": "Ingénierie - Multidisciplinaire", "city": "Montréal, QC", "careers": "https://www.cimaplus.com/carrieres", "poste": "Ingénieur électrique", "type": "generale"},
    {"company": "BBA", "sector": "Ingénierie - Mines", "city": "Québec, QC", "careers": "https://www.bba.ca/careers", "poste": "Electrical Engineer - Mining", "type": "generale"},
    {"company": "Pageau Morel", "sector": "Ingénierie - Bâtiment", "city": "Montréal, QC", "careers": "https://www.pageaumorel.com/carrieres", "poste": "Building Electrical Engineer", "type": "generale"},
    {"company": "Bouthillette Parizeau", "sector": "Ingénierie - Bâtiment", "city": "Montréal, QC", "careers": "https://www.bpglobal.com/carrieres", "poste": "Ingénieur électrique", "type": "generale"},
    {"company": " exp", "sector": "Ingénierie - Multidisciplinaire", "city": "Québec, QC", "careers": "https://www.exp.com/careers", "poste": "Electrical Designer", "type": "generale"},
    {"company": "Tetra Tech", "sector": "Ingénierie - Environnement", "city": "Vancouver, BC", "careers": "https://www.tetratech.com/careers", "poste": "Substation Engineer", "type": "generale"},
    {"company": "Hatch", "sector": "Ingénierie - Mines/Métaux", "city": "Mississauga, ON", "careers": "https://www.hatch.com/careers", "poste": "Protection and Control Engineer", "type": "generale"},
    {"company": "Golder Associates (WSP)", "sector": "Ingénierie - Environnement", "city": "Calgary, AB", "careers": "https://www.wsp.com/careers", "poste": "MEP Engineer - Electrical", "type": "generale"},
    {"company": "Worley", "sector": "Ingénierie - Énergie", "city": "Calgary, AB", "careers": "https://www.worley.com/careers", "poste": "Electrical Engineer - Oil & Gas", "type": "generale"},
    {"company": "Black & McDonald", "sector": "Construction - Électrique", "city": "Toronto, ON", "careers": "https://www.blackandmcdonald.com/careers", "poste": "Commissioning Engineer", "type": "generale"},
    {"company": "Pomerleau", "sector": "Construction", "city": "Québec, QC", "careers": "https://www.pomerleau.ca/carrieres", "poste": "Electrical Engineer - Construction", "type": "generale"},
    {"company": "Aecon", "sector": "Construction - Infrastructure", "city": "Toronto, ON", "careers": "https://www.aecon.com/careers", "poste": "Electrical Engineer - Infrastructure", "type": "generale"},
    {"company": "EBC Inc.", "sector": "Construction", "city": "Québec, QC", "careers": "https://www.ebcinc.ca/carrieres", "poste": "Ingénieur électrique", "type": "generale"},
    {"company": "Borea Construction", "sector": "Construction", "city": "Québec, QC", "careers": "https://www.borea.com/carrieres", "poste": "Coordonnateur électrique", "type": "supervision"},
    {"company": "Groupe Canam", "sector": "Construction - Acier", "city": "Montréal, QC", "careers": "https://www.canamgroup.com/carrieres", "poste": "Electrical Engineer - Industrial", "type": "generale"},
    {"company": "Maisons Laprise", "sector": "Construction - Résidentiel", "city": "Québec, QC", "careers": "https://www.maisonslaprise.com/carrieres", "poste": "Électricien industriel", "type": "maintenance"},
    
    # UTILITIES / ÉNERGIE
    {"company": "Hydro-Québec", "sector": "Utility - Électricité", "city": "Montréal, QC", "careers": "https://www.hydroquebec.com/carrieres", "poste": "Ingénieur électrique", "type": "generale"},
    {"company": "Ontario Power Generation (OPG)", "sector": "Utility - Nucléaire/Hydro", "city": "Toronto, ON", "careers": "https://www.opg.com/careers", "poste": "Electrical Engineer - Power Generation", "type": "generale"},
    {"company": "Bruce Power", "sector": "Utility - Nucléaire", "city": "Tiverton, ON", "careers": "https://www.brucepower.com/careers", "poste": "Electrical Engineer - Nuclear", "type": "generale"},
    {"company": "Manitoba Hydro", "sector": "Utility - Électricité", "city": "Winnipeg, MB", "careers": "https://www.hydro.mb.ca/careers", "poste": "Power Systems Engineer", "type": "generale"},
    {"company": "BC Hydro", "sector": "Utility - Électricité", "city": "Vancouver, BC", "careers": "https://www.bchydro.com/careers", "poste": "Electrical Engineer - Utilities", "type": "generale"},
    {"company": "Nova Scotia Power", "sector": "Utility - Électricité", "city": "Halifax, NS", "careers": "https://www.nspower.ca/careers", "poste": "Relay Engineer", "type": "generale"},
    {"company": "Toronto Hydro", "sector": "Utility - Distribution", "city": "Toronto, ON", "careers": "https://www.torontohydro.com/careers", "poste": "Distribution Engineer", "type": "generale"},
    {"company": "Énergir", "sector": "Utility - Gaz naturel", "city": "Montréal, QC", "careers": "https://www.energir.com/carrieres", "poste": "Energy Engineer", "type": "generale"},
    {"company": "TransGrid Solutions", "sector": "Consulting - Énergie", "city": "Montréal, QC", "careers": "https://www.transgrid.com/careers", "poste": "HV Electrical Engineer", "type": "generale"},
    {"company": "Columbia Basin Trust", "sector": "Utility - Hydro", "city": "Castlegar, BC", "careers": "https://www.cbt.org/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Columbia Power", "sector": "Utility - Hydro", "city": "Castlegar, BC", "careers": "https://www.columbiapower.org/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Northland Power", "sector": "Énergie renouvelable", "city": "Toronto, ON", "careers": "https://www.northlandpower.com/careers", "poste": "Renewable Energy Engineer", "type": "generale"},
    {"company": "EDF Renewables", "sector": "Énergie renouvelable", "city": "Toronto, ON", "careers": "https://www.edf-re.com/careers", "poste": "Electrical Engineer - Renewable Energy", "type": "generale"},
    {"company": "Natural Forces", "sector": "Énergie renouvelable", "city": "Dartmouth, NS", "careers": "https://www.naturalforces.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    
    # AUTOMATION / CONTRÔLE
    {"company": "Rockwell Automation", "sector": "Automation industrielle", "city": "Calgary, AB", "careers": "https://www.rockwellautomation.com/careers", "poste": "Automation Engineer", "type": "automatisation"},
    {"company": "ABB", "sector": "Électrification / Automation", "city": "Burlington, ON", "careers": "https://www.abb.com/careers", "poste": "Controls Engineer", "type": "automatisation"},
    {"company": "Schneider Electric", "sector": "Énergie / Automation", "city": "Montréal, QC", "careers": "https://www.se.com/careers", "poste": "Field Service Engineer", "type": "automatisation"},
    {"company": "Emerson", "sector": "Automation / Instrumentation", "city": "Edmonton, AB", "careers": "https://www.emerson.com/careers", "poste": "Instrumentation Engineer", "type": "automatisation"},
    {"company": "Siemens Mobility", "sector": "Transport / Automation", "city": "Montréal, QC", "careers": "https://www.mobility.siemens.com/careers", "poste": "Electrical Engineer - Transportation", "type": "automatisation"},
    {"company": "Siemens Canada", "sector": "Énergie / Automation", "city": "Oakville, ON", "careers": "https://www.siemens.com/careers", "poste": "Electrical Engineer", "type": "automatisation"},
    {"company": "Johnson Controls", "sector": "Bâtiment intelligent", "city": "Toronto, ON", "careers": "https://www.johnsoncontrols.com/careers", "poste": "Building Automation Engineer", "type": "automatisation"},
    {"company": "Honeywell", "sector": "Aérospatial / Automation", "city": "Montréal, QC", "careers": "https://www.honeywell.com/careers", "poste": "Electrical Engineer", "type": "automatisation"},
    {"company": "Itron", "sector": "Smart Grid", "city": "Oakville, ON", "careers": "https://www.itron.com/careers", "poste": "Electrical Engineer - Smart Grid", "type": "automatisation"},
    {"company": "GE Vernova", "sector": "Énergie / Éolien", "city": "Montréal, QC", "careers": "https://www.gevernova.com/careers", "poste": "Electrical Engineer", "type": "automatisation"},
    {"company": "Danfoss", "sector": "Automation / HVAC", "city": "Toronto, ON", "careers": "https://www.danfoss.com/careers", "poste": "Application Engineer", "type": "automatisation"},
    {"company": "Yokogawa", "sector": "Instrumentation / Contrôle", "city": "Calgary, AB", "careers": "https://www.yokogawa.com/careers", "poste": "Control Systems Engineer", "type": "automatisation"},
    
    # MANUFACTURIER / MINES
    {"company": "Rio Tinto", "sector": "Mines - Aluminium", "city": "Saguenay, QC", "careers": "https://www.riotinto.com/careers", "poste": "Electrical Maintenance Engineer", "type": "maintenance"},
    {"company": "ArcelorMittal", "sector": "Mines / Acier", "city": "Contrecoeur, QC", "careers": "https://www.arcelormittal.com/careers", "poste": "Electrical Maintenance Supervisor", "type": "supervision"},
    {"company": "Bombardier", "sector": "Transport / Aéronautique", "city": "Montréal, QC", "careers": "https://www.bombardier.com/careers", "poste": "Electrical Engineer - Manufacturing", "type": "generale"},
    {"company": "Pratt & Whitney Canada", "sector": "Aéronautique / Moteurs", "city": "Longueuil, QC", "careers": "https://www.pwc.ca/careers", "poste": "Electrical Engineer - Aerospace", "type": "generale"},
    {"company": "Caterpillar", "sector": "Machinerie lourde", "city": "Lively, ON", "careers": "https://www.caterpillar.com/careers", "poste": "Electrical Engineer - Mining Equipment", "type": "generale"},
    {"company": "TM4 (Dana)", "sector": "Motorisation électrique", "city": "Boucherville, QC", "careers": "https://www.dana.com/careers", "poste": "Power Electronics Engineer", "type": "generale"},
    {"company": "Orica", "sector": "Mines / Explosifs", "city": "Brownsburg, QC", "careers": "https://www.orica.com/careers", "poste": "Plant Electrical Engineer", "type": "generale"},
    {"company": "Aluminerie Alouette", "sector": "Mines - Aluminium", "city": "Sept-Îles, QC", "careers": "https://www.alouette.qc.ca/carrieres", "poste": "Ingénieur(e) en automatisme", "type": "automatisation"},
    {"company": "Alcoa", "sector": "Mines - Aluminium", "city": "Baie-Comeau, QC", "careers": "https://www.alcoa.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Vale Canada", "sector": "Mines - Nickel", "city": "Sudbury, ON", "careers": "https://www.vale.com/canada/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Glencore", "sector": "Mines - Cuivre/Zinc", "city": "Rouyn-Noranda, QC", "careers": "https://www.glencore.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Newmont", "sector": "Mines - Or", "city": "Timmins, ON", "careers": "https://www.newmont.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "IAMGOLD", "sector": "Mines - Or", "city": "Rouyn-Noranda, QC", "careers": "https://www.iamgold.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Resolute Forest Products", "sector": "Pâte et papier", "city": "Montréal, QC", "careers": "https://www.resolutefp.com/careers", "poste": "Electrical Engineer - Pulp & Paper", "type": "generale"},
    {"company": "Domtar", "sector": "Pâte et papier", "city": "Montréal, QC", "careers": "https://www.domtar.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Olymel", "sector": "Agroalimentaire", "city": "Saint-Hyacinthe, QC", "careers": "https://www.olymel.com/carrieres", "poste": "Electrical Engineer - Food Industry", "type": "generale"},
    {"company": "Saputo", "sector": "Agroalimentaire", "city": "Montréal, QC", "careers": "https://www.saputo.com/careers", "poste": "Electrical Maintenance Engineer", "type": "maintenance"},
    {"company": "Maple Leaf Foods", "sector": "Agroalimentaire", "city": "Toronto, ON", "careers": "https://www.mapleleaffoods.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Pfizer Canada", "sector": "Pharmaceutique", "city": "Kirkland, QC", "careers": "https://www.pfizer.ca/careers", "poste": "Electrical Engineer - Pharmaceutical", "type": "generale"},
    {"company": "Merck Canada", "sector": "Pharmaceutique", "city": "Kirkland, QC", "careers": "https://www.merck.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Sanofi", "sector": "Pharmaceutique", "city": "Toronto, ON", "careers": "https://www.sanofi.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    
    # TÉLÉCOMMUNICATIONS / TECHNOLOGIE
    {"company": "Bell Canada", "sector": "Télécommunications", "city": "Montréal, QC", "careers": "https://www.bell.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Ericsson Canada", "sector": "Télécommunications", "city": "Montréal, QC", "careers": "https://www.ericsson.com/careers", "poste": "Electrical Engineer - Telecommunications", "type": "generale"},
    {"company": "Thales Canada", "sector": "Défense / Transport", "city": "Toronto, ON", "careers": "https://www.thalesgroup.com/careers", "poste": "Electrical Systems Engineer", "type": "generale"},
    {"company": "CAE", "sector": "Simulation aéronautique", "city": "Montréal, QC", "careers": "https://www.cae.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "IBM Canada", "sector": "Technologie / Services", "city": "Markham, ON", "careers": "https://www.ibm.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Ciena", "sector": "Réseaux optiques", "city": "Ottawa, ON", "careers": "https://www.ciena.com/careers", "poste": "Hardware Engineer", "type": "generale"},
    {"company": "Nokia Canada", "sector": "Télécommunications", "city": "Ottawa, ON", "careers": "https://www.nokia.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    
    # GOUVERNEMENT / MUNICIPALITÉS
    {"company": "Ville de Montréal", "sector": "Municipal", "city": "Montréal, QC", "careers": "https://montreal.ca/careers", "poste": "Ingénieur électrique", "type": "generale"},
    {"company": "Ville de Québec", "sector": "Municipal", "city": "Québec, QC", "careers": "https://www.ville.quebec.qc.ca/carrieres", "poste": "Ingénieur électrique", "type": "generale"},
    {"company": "Ville de Toronto", "sector": "Municipal", "city": "Toronto, ON", "careers": "https://www.toronto.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Ville d'Ottawa", "sector": "Municipal", "city": "Ottawa, ON", "careers": "https://jobs.ottawa.ca", "poste": "Electrical Engineer - Municipal", "type": "generale"},
    {"company": "Ville de Vancouver", "sector": "Municipal", "city": "Vancouver, BC", "careers": "https://vancouver.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Transports Canada", "sector": "Gouvernement fédéral", "city": "Ottawa, ON", "careers": "https://www.canada.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Défense nationale", "sector": "Gouvernement fédéral", "city": "Ottawa, ON", "careers": "https://www.canada.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Parcs Canada", "sector": "Gouvernement fédéral", "city": "Québec, QC", "careers": "https://www.canada.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    
    # CONSULTING / AUTRES
    {"company": "Brookfield Properties", "sector": "Immobilier", "city": "Toronto, ON", "careers": "https://www.brookfieldproperties.com/careers", "poste": "Electrical Engineer - HVAC", "type": "generale"},
    {"company": "Cushman & Wakefield", "sector": "Immobilier / Facilities", "city": "Toronto, ON", "careers": "https://www.cushmanwakefield.com/careers", "poste": "Electrical Engineer - Data Centers", "type": "generale"},
    {"company": "QuadReal", "sector": "Immobilier", "city": "Vancouver, BC", "careers": "https://www.quadreal.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "GM BluePlan", "sector": "Ingénierie - Eau", "city": "Markham, ON", "careers": "https://www.gmblueplan.ca/careers", "poste": "Electrical Engineer - Water/Wastewater", "type": "generale"},
    {"company": "CSA Group", "sector": "Normes / Certification", "city": "Toronto, ON", "careers": "https://www.csagroup.org/careers", "poste": "Electrical Safety Engineer", "type": "generale"},
    {"company": "LabTest Certification", "sector": "Certification", "city": "Richmond, BC", "careers": "https://www.labtest.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Fed Manutech", "sector": "Manufacturier", "city": "Blainville, QC", "careers": "https://www.fedmanutech.com/carrieres", "poste": "Electrical network engineer", "type": "automatisation"},
    {"company": "Inviro Engineered Systems", "sector": "Ingénierie - Bâtiment", "city": "Toronto, ON", "careers": "https://www.inviro.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Brunel", "sector": "Recrutement technique", "city": "Vancouver, BC", "careers": "https://www.brunel.net/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "TWD Technologies", "sector": "Construction électrique", "city": "Toronto, ON", "careers": "https://www.twdtech.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Peter Lucas Project Management", "sector": "Gestion de projet", "city": "Saskatoon, SK", "careers": "https://www.peterlucas.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Englobe Corp", "sector": "Ingénierie - Environnement", "city": "Montréal, QC", "careers": "https://www.englobecorp.com/carrieres", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Creative Door Services", "sector": "Construction", "city": "Edmonton, AB", "careers": "https://www.creativedoor.com/careers", "poste": "Electrical technician", "type": "maintenance"},
    {"company": "Metro Vancouver", "sector": "Municipal", "city": "Vancouver, BC", "careers": "https://www.metrovancouver.org/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Hydel Inc.", "sector": "Construction électrique", "city": "Toronto, ON", "careers": "https://www.hydel.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Integrated Power Services", "sector": "Maintenance électrique", "city": "Sherbrooke, QC", "careers": "https://www.ips.us/careers", "poste": "Electrical technician", "type": "maintenance"},
    {"company": "Vitrerie Vaillancourt", "sector": "Construction", "city": "Victoriaville, QC", "careers": "https://www.vitrerievaillancourt.com/carrieres", "poste": "Electrical technician", "type": "maintenance"},
    {"company": "Vantage Data Centers", "sector": "Data Centers", "city": "Pointe-Claire, QC", "careers": "https://www.vantagedc.com/careers", "poste": "Electrical technician", "type": "maintenance"},
    {"company": "Simple Staffing", "sector": "Recrutement", "city": "Victoria, BC", "careers": "https://www.simplestaffing.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Nova Scotia Power", "sector": "Utility", "city": "Halifax, NS", "careers": "https://www.nspower.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    
    # AJOUTS POUR ATTEINDRE 200+
    {"company": "Lafarge Canada", "sector": "Construction - Matériaux", "city": "Montréal, QC", "careers": "https://www.lafarge.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Holcim Canada", "sector": "Construction - Matériaux", "city": "Montréal, QC", "careers": "https://www.holcim.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Colas Canada", "sector": "Construction - Routes", "city": "Montréal, QC", "careers": "https://www.colas.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Développement électrique de l'Ouest (DELO)", "sector": "Construction électrique", "city": "Edmonton, AB", "careers": "https://www.delo.ca/carrieres", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Groupe Atwill-Morin", "sector": "Construction", "city": "Montréal, QC", "careers": "https://www.atwill-morin.com/carrieres", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Groupe DCM", "sector": "Construction", "city": "Montréal, QC", "careers": "https://www.dcm.ca/carrieres", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Grasby", "sector": "Mécanique / Électrique", "city": "Toronto, ON", "careers": "https://www.grasby.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "EllisDon", "sector": "Construction", "city": "Mississauga, ON", "careers": "https://www.ellisdon.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Stuart Olson", "sector": "Construction", "city": "Calgary, AB", "careers": "https://www.stuartolson.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "PCL Construction", "sector": "Construction", "city": "Edmonton, AB", "careers": "https://www.pcl.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Ledcor", "sector": "Construction / Télécom", "city": "Vancouver, BC", "careers": "https://www.ledcor.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Graham Construction", "sector": "Construction", "city": "Calgary, AB", "careers": "https://www.graham.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Bird Construction", "sector": "Construction", "city": "Winnipeg, MB", "careers": "https://www.bird.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Magil Construction", "sector": "Construction", "city": "Montréal, QC", "careers": "https://www.magil.com/carrieres", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Dessau (CIMA+)", "sector": "Ingénierie", "city": "Montréal, QC", "careers": "https://www.cimaplus.com/carrieres", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "AECOM", "sector": "Ingénierie", "city": "Montréal, QC", "careers": "https://www.aecom.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Jacobs", "sector": "Ingénierie", "city": "Montréal, QC", "careers": "https://www.jacobs.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Fluor Canada", "sector": "Ingénierie - Énergie", "city": "Calgary, AB", "careers": "https://www.fluor.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Bechtel", "sector": "Ingénierie - Énergie", "city": "Calgary, AB", "careers": "https://www.bechtel.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "McElhanney", "sector": "Ingénierie", "city": "Vancouver, BC", "careers": "https://www.mcelhanney.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Associated Engineering", "sector": "Ingénierie", "city": "Edmonton, AB", "careers": "https://www.ae.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Kerr Wood Leidal", "sector": "Ingénierie - Environnement", "city": "Vancouver, BC", "careers": "https://www.kwl.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "ISL Engineering", "sector": "Ingénierie", "city": "Edmonton, AB", "careers": "https://www.islengineering.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Morrison Hershfield", "sector": "Ingénierie - Bâtiment", "city": "Markham, ON", "careers": "https://www.morrisonhershfield.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Read Jones Christoffersen (RJC)", "sector": "Ingénierie - Structure", "city": "Vancouver, BC", "careers": "https://www.rjc.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Smith + Andersen", "sector": "Ingénierie - Mécanique/Électrique", "city": "Toronto, ON", "careers": "https://www.smithandandersen.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "The Mitchell Partnership", "sector": "Ingénierie - Mécanique", "city": "Toronto, ON", "careers": "https://www.tmp.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Crossey Engineering", "sector": "Ingénierie - Électrique", "city": "Ottawa, ON", "careers": "https://www.crosseyengineering.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Cushman & Wakefield", "sector": "Facilities Management", "city": "Toronto, ON", "careers": "https://www.cushmanwakefield.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "JLL", "sector": "Facilities / Immobilier", "city": "Toronto, ON", "careers": "https://www.jll.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "CBRE", "sector": "Facilities / Immobilier", "city": "Toronto, ON", "careers": "https://www.cbre.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "BGIS", "sector": "Facilities Management", "city": "Toronto, ON", "careers": "https://www.bgis.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Compass Group Canada", "sector": "Services alimentaires", "city": "Mississauga, ON", "careers": "https://www.compass-canada.com/careers", "poste": "Electrical Maintenance", "type": "maintenance"},
    {"company": "Aramark Canada", "sector": "Services", "city": "Toronto, ON", "careers": "https://www.aramark.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Sodexo Canada", "sector": "Services", "city": "Montréal, QC", "careers": "https://www.sodexo.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Ivanhoé Cambridge", "sector": "Immobilier", "city": "Montréal, QC", "careers": "https://www.ivanhoecambridge.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Cadillac Fairview", "sector": "Immobilier", "city": "Toronto, ON", "careers": "https://www.cadillacfairview.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Oxford Properties", "sector": "Immobilier", "city": "Toronto, ON", "careers": "https://www.oxfordproperties.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Allied Properties REIT", "sector": "Immobilier", "city": "Toronto, ON", "careers": "https://www.alliedproperties.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Dream Unlimited", "sector": "Immobilier", "city": "Toronto, ON", "careers": "https://www.dream.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Pembina Pipeline", "sector": "Oléoducs", "city": "Calgary, AB", "careers": "https://www.pembina.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Enbridge", "sector": "Oléoducs", "city": "Calgary, AB", "careers": "https://www.enbridge.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "TC Energy", "sector": "Oléoducs", "city": "Calgary, AB", "careers": "https://www.tcenergy.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Keyera", "sector": "Énergie", "city": "Calgary, AB", "careers": "https://www.keyera.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Inter Pipeline", "sector": "Oléoducs", "city": "Calgary, AB", "careers": "https://www.interpipeline.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Cenovus Energy", "sector": "Pétrole et gaz", "city": "Calgary, AB", "careers": "https://www.cenovus.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Canadian Natural Resources", "sector": "Pétrole et gaz", "city": "Calgary, AB", "careers": "https://www.cnrl.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Imperial Oil", "sector": "Pétrole et gaz", "city": "Calgary, AB", "careers": "https://www.imperialoil.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Husky Energy (Cenovus)", "sector": "Pétrole et gaz", "city": "Calgary, AB", "careers": "https://www.cenovus.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Suncor Energy", "sector": "Pétrole et gaz", "city": "Calgary, AB", "careers": "https://www.suncor.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Syncrude", "sector": "Sables bitumineux", "city": "Fort McMurray, AB", "careers": "https://www.syncrude.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Teck Resources", "sector": "Mines - Cuivre/Charbon", "city": "Vancouver, BC", "careers": "https://www.teck.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "First Quantum Minerals", "sector": "Mines - Cuivre", "city": "Toronto, ON", "careers": "https://www.first-quantum.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Lundin Mining", "sector": "Mines - Cuivre/Zinc", "city": "Toronto, ON", "careers": "https://www.lundinmining.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Nutrien", "sector": "Agriculture / Mines", "city": "Saskatoon, SK", "careers": "https://www.nutrien.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "PotashCorp (Nutrien)", "sector": "Mines - Potasse", "city": "Saskatoon, SK", "careers": "https://www.nutrien.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Mosaic", "sector": "Mines - Potasse", "city": "Regina, SK", "careers": "https://www.mosaicco.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Agrium (Nutrien)", "sector": "Agriculture", "city": "Calgary, AB", "careers": "https://www.nutrien.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Air Canada", "sector": "Transport aérien", "city": "Montréal, QC", "careers": "https://www.aircanada.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "WestJet", "sector": "Transport aérien", "city": "Calgary, AB", "careers": "https://www.westjet.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "VIA Rail", "sector": "Transport ferroviaire", "city": "Montréal, QC", "careers": "https://www.viarail.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "CN Rail", "sector": "Transport ferroviaire", "city": "Montréal, QC", "careers": "https://www.cn.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "CPKC (Canadian Pacific Kansas City)", "sector": "Transport ferroviaire", "city": "Calgary, AB", "careers": "https://www.cpkcr.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Port of Vancouver", "sector": "Transport maritime", "city": "Vancouver, BC", "careers": "https://www.portvancouver.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Port of Montréal", "sector": "Transport maritime", "city": "Montréal, QC", "careers": "https://www.port-montreal.com/carrieres", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Autorité portuaire de Québec", "sector": "Transport maritime", "city": "Québec, QC", "careers": "https://www.portquebec.ca/carrieres", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "STM (Société de transport de Montréal)", "sector": "Transport en commun", "city": "Montréal, QC", "careers": "https://www.stm.info/carrieres", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "TTC (Toronto Transit Commission)", "sector": "Transport en commun", "city": "Toronto, ON", "careers": "https://www.ttc.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "TransLink", "sector": "Transport en commun", "city": "Vancouver, BC", "careers": "https://www.translink.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "OC Transpo", "sector": "Transport en commun", "city": "Ottawa, ON", "careers": "https://www.octranspo.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Calgary Transit", "sector": "Transport en commun", "city": "Calgary, AB", "careers": "https://www.calgarytransit.com/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Hôpital général de Montréal (CUSM)", "sector": "Santé", "city": "Montréal, QC", "careers": "https://www.cusm.ca/carrieres", "poste": "Electrical Maintenance", "type": "maintenance"},
    {"company": "CHU de Québec", "sector": "Santé", "city": "Québec, QC", "careers": "https://www.chudequebec.ca/carrieres", "poste": "Electrical Maintenance", "type": "maintenance"},
    {"company": "Sunnybrook Health Sciences", "sector": "Santé", "city": "Toronto, ON", "careers": "https://www.sunnybrook.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "University Health Network", "sector": "Santé", "city": "Toronto, ON", "careers": "https://www.uhn.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "McGill University Health Centre", "sector": "Santé", "city": "Montréal, QC", "careers": "https://www.muhc.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Concordia University", "sector": "Éducation", "city": "Montréal, QC", "careers": "https://www.concordia.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "McGill University", "sector": "Éducation", "city": "Montréal, QC", "careers": "https://www.mcgill.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Université de Montréal", "sector": "Éducation", "city": "Montréal, QC", "careers": "https://www.umontreal.ca/carrieres", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "UQAT", "sector": "Éducation", "city": "Rouyn-Noranda, QC", "careers": "https://www.uqat.ca/carrieres", "poste": "Technicien électrique", "type": "maintenance"},
    {"company": "Université Laval", "sector": "Éducation", "city": "Québec, QC", "careers": "https://www.ulaval.ca/carrieres", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Université de Sherbrooke", "sector": "Éducation", "city": "Sherbrooke, QC", "careers": "https://www.usherbrooke.ca/carrieres", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Polytechnique Montréal", "sector": "Éducation", "city": "Montréal, QC", "careers": "https://www.polymtl.ca/carrieres", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "ÉTS (École de technologie supérieure)", "sector": "Éducation", "city": "Montréal, QC", "careers": "https://www.etsmtl.ca/carrieres", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "University of Toronto", "sector": "Éducation", "city": "Toronto, ON", "careers": "https://www.utoronto.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "University of British Columbia", "sector": "Éducation", "city": "Vancouver, BC", "careers": "https://www.ubc.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "University of Alberta", "sector": "Éducation", "city": "Edmonton, AB", "careers": "https://www.ualberta.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Dalhousie University", "sector": "Éducation", "city": "Halifax, NS", "careers": "https://www.dal.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Carleton University", "sector": "Éducation", "city": "Ottawa, ON", "careers": "https://www.carleton.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Queen's University", "sector": "Éducation", "city": "Kingston, ON", "careers": "https://www.queensu.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Western University", "sector": "Éducation", "city": "London, ON", "careers": "https://www.uwo.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "McMaster University", "sector": "Éducation", "city": "Hamilton, ON", "careers": "https://www.mcmaster.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Université du Nouveau-Brunswick", "sector": "Éducation", "city": "Fredericton, NB", "careers": "https://www.unb.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Université de Moncton", "sector": "Éducation", "city": "Moncton, NB", "careers": "https://www.umoncton.ca/carrieres", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Memorial University", "sector": "Éducation", "city": "St. John's, NL", "careers": "https://www.mun.ca/careers", "poste": "Electrical Engineer", "type": "generale"},
    {"company": "Red River College Polytech", "sector": "Éducation", "city": "Winnipeg, MB", "careers": "https://www.rrc.ca/careers", "poste": "Electrical Instructor", "type": "generale"},
    {"company": "SAIT", "sector": "Éducation", "city": "Calgary, AB", "careers": "https://www.sait.ca/careers", "poste": "Electrical Instructor", "type": "generale"},
    {"company": "BCIT", "sector": "Éducation", "city": "Burnaby, BC", "careers": "https://www.bcit.ca/careers", "poste": "Electrical Instructor", "type": "generale"},
    {"company": "Conestoga College", "sector": "Éducation", "city": "Kitchener, ON", "careers": "https://www.conestogac.on.ca/careers", "poste": "Electrical Instructor", "type": "generale"},
    {"company": "Humber College", "sector": "Éducation", "city": "Toronto, ON", "careers": "https://www.humber.ca/careers", "poste": "Electrical Instructor", "type": "generale"},
    {"company": "Seneca College", "sector": "Éducation", "city": "Toronto, ON", "careers": "https://www.senecacollege.ca/careers", "poste": "Electrical Instructor", "type": "generale"},
    {"company": "Centennial College", "sector": "Éducation", "city": "Toronto, ON", "careers": "https://www.centennialcollege.ca/careers", "poste": "Electrical Instructor", "type": "generale"},
    {"company": "George Brown College", "sector": "Éducation", "city": "Toronto, ON", "careers": "https://www.georgebrown.ca/careers", "poste": "Electrical Instructor", "type": "generale"},
    {"company": "Sheridan College", "sector": "Éducation", "city": "Oakville, ON", "careers": "https://www.sheridancollege.ca/careers", "poste": "Electrical Instructor", "type": "generale"},
    {"company": "Mohawk College", "sector": "Éducation", "city": "Hamilton, ON", "careers": "https://www.mohawkcollege.ca/careers", "poste": "Electrical Instructor", "type": "generale"},
    {"company": "Fanshawe College", "sector": "Éducation", "city": "London, ON", "careers": "https://www.fanshawec.ca/careers", "poste": "Electrical Instructor", "type": "generale"},
    {"company": "Algonquin College", "sector": "Éducation", "city": "Ottawa, ON", "careers": "https://www.algonquincollege.com/careers", "poste": "Electrical Instructor", "type": "generale"},
    {"company": "Cégep de Saint-Laurent", "sector": "Éducation", "city": "Montréal, QC", "careers": "https://www.cegepsl.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep du Vieux Montréal", "sector": "Éducation", "city": "Montréal, QC", "careers": "https://www.cvm.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep Édouard-Montpetit", "sector": "Éducation", "city": "Longueuil, QC", "careers": "https://www.cegepmontpetit.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de Sherbrooke", "sector": "Éducation", "city": "Sherbrooke, QC", "careers": "https://www.cegepsherbrooke.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de Trois-Rivières", "sector": "Éducation", "city": "Trois-Rivières, QC", "careers": "https://www.cegeptr.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de Victoriaville", "sector": "Éducation", "city": "Victoriaville, QC", "careers": "https://www.cegep-victo.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de Sorel-Tracy", "sector": "Éducation", "city": "Sorel-Tracy, QC", "careers": "https://www.cegep-sorel-tracy.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de Jonquière", "sector": "Éducation", "city": "Jonquière, QC", "careers": "https://www.cegepjonquiere.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de Chicoutimi", "sector": "Éducation", "city": "Chicoutimi, QC", "careers": "https://www.cegepchicoutimi.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de Rimouski", "sector": "Éducation", "city": "Rimouski, QC", "careers": "https://www.cegep-rimouski.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de Baie-Comeau", "sector": "Éducation", "city": "Baie-Comeau, QC", "careers": "https://www.cegepbc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de Sept-Îles", "sector": "Éducation", "city": "Sept-Îles, QC", "careers": "https://www.cegep-sept-iles.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de Saint-Jérôme", "sector": "Éducation", "city": "Saint-Jérôme, QC", "careers": "https://www.cegepst-jerome.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep régional de Lanaudière", "sector": "Éducation", "city": "Joliette, QC", "careers": "https://www.cegep-lanaudiere.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de Valleyfield", "sector": "Éducation", "city": "Salaberry-de-Valleyfield, QC", "careers": "https://www.cegep-valleyfield.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de l'Outaouais", "sector": "Éducation", "city": "Gatineau, QC", "careers": "https://www.cegep-outaouais.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de l'Abitibi-Témiscamingue", "sector": "Éducation", "city": "Rouyn-Noranda, QC", "careers": "https://www.cegepat.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de Granby", "sector": "Éducation", "city": "Granby, QC", "careers": "https://www.cegepgranby.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de Matane", "sector": "Éducation", "city": "Matane, QC", "careers": "https://www.cegepmatane.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de Rivière-du-Loup", "sector": "Éducation", "city": "Rivière-du-Loup, QC", "careers": "https://www.cegep-rdl.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de Thetford", "sector": "Éducation", "city": "Thetford Mines, QC", "careers": "https://www.cegep-thetford.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de Saint-Hyacinthe", "sector": "Éducation", "city": "Saint-Hyacinthe, QC", "careers": "https://www.cegep-st-hyacinthe.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de Drummondville", "sector": "Éducation", "city": "Drummondville, QC", "careers": "https://www.cegep-drummond.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de Sainte-Foy", "sector": "Éducation", "city": "Québec, QC", "careers": "https://www.cegep-ste-foy.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep Limoilou", "sector": "Éducation", "city": "Québec, QC", "careers": "https://www.cegeplimoilou.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep Garneau", "sector": "Éducation", "city": "Québec, QC", "careers": "https://www.cegepgarneau.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de Lévis-Lauzon", "sector": "Éducation", "city": "Lévis, QC", "careers": "https://www.cegeplevis.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de La Pocatière", "sector": "Éducation", "city": "La Pocatière, QC", "careers": "https://www.cegep-lapocatiere.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de Alma", "sector": "Éducation", "city": "Alma, QC", "careers": "https://www.cegepalma.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de Saint-Jean-sur-Richelieu", "sector": "Éducation", "city": "Saint-Jean-sur-Richelieu, QC", "careers": "https://www.cegep-st-jean.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Vanier College", "sector": "Éducation", "city": "Montréal, QC", "careers": "https://www.vaniercollege.qc.ca/careers", "poste": "Electrical Instructor", "type": "generale"},
    {"company": "Dawson College", "sector": "Éducation", "city": "Montréal, QC", "careers": "https://www.dawsoncollege.qc.ca/careers", "poste": "Electrical Instructor", "type": "generale"},
    {"company": "John Abbott College", "sector": "Éducation", "city": "Sainte-Anne-de-Bellevue, QC", "careers": "https://www.johnabbott.qc.ca/careers", "poste": "Electrical Instructor", "type": "generale"},
    {"company": "Champlain College", "sector": "Éducation", "city": "Sherbrooke, QC", "careers": "https://www.champlainonline.com/careers", "poste": "Electrical Instructor", "type": "generale"},
    {"company": "Heritage College", "sector": "Éducation", "city": "Gatineau, QC", "careers": "https://www.cegep-heritage.qc.ca/carrieres", "poste": "Electrical Instructor", "type": "generale"},
    {"company": "TÉLUQ", "sector": "Éducation", "city": "Québec, QC", "careers": "https://www.teluq.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Institut de technologie agroalimentaire", "sector": "Éducation", "city": "La Pocatière, QC", "careers": "https://www.ita.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Institut maritime du Québec", "sector": "Éducation", "city": "Rimouski, QC", "careers": "https://www.imq.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de Maisonneuve", "sector": "Éducation", "city": "Montréal, QC", "careers": "https://www.cegep-montpetit.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep André-Laurendeau", "sector": "Éducation", "city": "Montréal, QC", "careers": "https://www.cegeplaurendeau.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep Marie-Victorin", "sector": "Éducation", "city": "Montréal, QC", "careers": "https://www.collegemv.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep régional de Lanaudière à Terrebonne", "sector": "Éducation", "city": "Terrebonne, QC", "careers": "https://www.cegep-lanaudiere.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de Saint-Félicien", "sector": "Éducation", "city": "Saint-Félicien, QC", "careers": "https://www.cegep-st-felicien.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de Victoriaville", "sector": "Éducation", "city": "Victoriaville, QC", "careers": "https://www.cegep-victo.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep Beauce-Appalaches", "sector": "Éducation", "city": "Saint-Georges, QC", "careers": "https://www.cegepbea.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
    {"company": "Cégep de La Pocatière", "sector": "Éducation", "city": "La Pocatière, QC", "careers": "https://www.cegep-lapocatiere.qc.ca/carrieres", "poste": "Professeur électrotechnique", "type": "generale"},
]

print(f"Nombre total d'entreprises : {len(companies)}")

# Ajouter les champs manquants
for i, c in enumerate(companies, 1):
    c['num'] = i
    c['title'] = c['poste']
    c['location'] = c['city']
    c['salary'] = 'À vérifier sur le site'
    c['link'] = c['careers']
    c['date'] = 'Août 2026'
    c['status'] = 'À postuler'
    c['date_postulation'] = ''

# Sauvegarder
with open('entreprises_200_plus.json', 'w', encoding='utf-8') as f:
    json.dump(companies, f, ensure_ascii=False, indent=2)

print(f"\n✓ entreprises_200_plus.json créé avec {len(companies)} entreprises")

# Statistiques
sectors = {}
for c in companies:
    sectors[c['sector']] = sectors.get(c['sector'], 0) + 1

print(f"\nRépartition par secteur:")
for sector, count in sorted(sectors.items(), key=lambda x: -x[1])[:15]:
    print(f"  {sector}: {count}")
